title: Ari Stathopoulos
description: Software Architect, Accessibility & Sustainability evangelist, Human.
url: https://aristath.github.io
author: Ari Stathopoulos
lang: en

twitter:
  username: aristath
  card: summary_large_image

social:
  name: Ari Stathopoulos
  links:
    - https://twitter.com/aristath
    - https://github.com/aristath

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

paginate: 6
paginate_path: "/blog/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  